                                                                                                                                                                                                                                                                                        /** ojsa */

                     
var skeletalMap = {atlas:'res/3d-objects/human/skeletal/atlas.obj' , 
axis:'res/3d-objects/human/skeletal/axis.obj' , 
body_of_sternum:'res/3d-objects/human/skeletal/body of sternum.obj' , 
distal_phalanx_of_left_big_toe:'res/3d-objects/human/skeletal/distal phalanx of left big toe.obj' , 
distal_phalanx_of_left_fourth_toe:'res/3d-objects/human/skeletal/distal phalanx of left fourth toe.obj' , 
distal_phalanx_of_left_index_finger:'res/3d-objects/human/skeletal/distal phalanx of left index finger.obj' , 
distal_phalanx_of_left_little_finger:'res/3d-objects/human/skeletal/distal phalanx of left little finger.obj' , 
distal_phalanx_of_left_little_toe:'res/3d-objects/human/skeletal/distal phalanx of left little toe.obj' , 
distal_phalanx_of_left_middle_finger:'res/3d-objects/human/skeletal/distal phalanx of left middle finger.obj' , 
distal_phalanx_of_left_ring_finger:'res/3d-objects/human/skeletal/distal phalanx of left ring finger.obj' , 
distal_phalanx_of_left_second_toe:'res/3d-objects/human/skeletal/distal phalanx of left second toe.obj' , 
distal_phalanx_of_left_third_toe:'res/3d-objects/human/skeletal/distal phalanx of left third toe.obj' , 
distal_phalanx_of_left_thumb:'res/3d-objects/human/skeletal/distal phalanx of left thumb.obj' , 
distal_phalanx_of_right_big_toe:'res/3d-objects/human/skeletal/distal phalanx of right big toe.obj' , 
distal_phalanx_of_right_fourth_toe:'res/3d-objects/human/skeletal/distal phalanx of right fourth toe.obj' , 
distal_phalanx_of_right_index_finger:'res/3d-objects/human/skeletal/distal phalanx of right index finger.obj' , 
distal_phalanx_of_right_little_finger:'res/3d-objects/human/skeletal/distal phalanx of right little finger.obj' , 
distal_phalanx_of_right_little_toe:'res/3d-objects/human/skeletal/distal phalanx of right little toe.obj' , 
distal_phalanx_of_right_middle_finger:'res/3d-objects/human/skeletal/distal phalanx of right middle finger.obj' , 
distal_phalanx_of_right_ring_finger:'res/3d-objects/human/skeletal/distal phalanx of right ring finger.obj' , 
distal_phalanx_of_right_second_toe:'res/3d-objects/human/skeletal/distal phalanx of right second toe.obj' , 
distal_phalanx_of_right_third_toe:'res/3d-objects/human/skeletal/distal phalanx of right third toe.obj' , 
distal_phalanx_of_right_thumb:'res/3d-objects/human/skeletal/distal phalanx of right thumb.obj' , 
eighth_thoracic_vertebra:'res/3d-objects/human/skeletal/eighth thoracic vertebra.obj' , 
eleventh_thoracic_vertebra:'res/3d-objects/human/skeletal/eleventh thoracic vertebra.obj' , 
ethmoid:'res/3d-objects/human/skeletal/ethmoid.obj' , 
fifth_cervical_vertebra:'res/3d-objects/human/skeletal/fifth cervical vertebra.obj' , 
fifth_lumbar_vertebra:'res/3d-objects/human/skeletal/fifth lumbar vertebra.obj' , 
fifth_thoracic_vertebra:'res/3d-objects/human/skeletal/fifth thoracic vertebra.obj' , 
first_lumbar_vertebra:'res/3d-objects/human/skeletal/first lumbar vertebra.obj' , 
first_thoracic_vertebra:'res/3d-objects/human/skeletal/first thoracic vertebra.obj' , 
flexor_retinaculum_of_left_wrist:'res/3d-objects/human/skeletal/flexor retinaculum of left wrist.obj' , 
flexor_retinaculum_of_right_wrist:'res/3d-objects/human/skeletal/flexor retinaculum of right wrist.obj' , 
fourth_cervical_vertebra:'res/3d-objects/human/skeletal/fourth cervical vertebra.obj' , 
fourth_lumbar_vertebra:'res/3d-objects/human/skeletal/fourth lumbar vertebra.obj' , 
fourth_thoracic_vertebra:'res/3d-objects/human/skeletal/fourth thoracic vertebra.obj' , 
frontal_bone:'res/3d-objects/human/skeletal/frontal bone.obj' , 
hyoid_bone:'res/3d-objects/human/skeletal/hyoid bone.obj' , 
hyoid_bone2:'res/3d-objects/human/skeletal/hyoid bone2.obj' , 
intervertebral_disk_of_axis:'res/3d-objects/human/skeletal/intervertebral disk of axis.obj' , 
intervertebral_disk_of_eighth_thoracic_vertebra:'res/3d-objects/human/skeletal/intervertebral disk of eighth thoracic vertebra.obj' , 
intervertebral_disk_of_eleventh_thoracic_vertebra:'res/3d-objects/human/skeletal/intervertebral disk of eleventh thoracic vertebra.obj' , 
intervertebral_disk_of_fifth_cervical_vertebra:'res/3d-objects/human/skeletal/intervertebral disk of fifth cervical vertebra.obj' , 
intervertebral_disk_of_fifth_lumbar_vertebra:'res/3d-objects/human/skeletal/intervertebral disk of fifth lumbar vertebra.obj' , 
intervertebral_disk_of_fifth_thoracic_vertebra:'res/3d-objects/human/skeletal/intervertebral disk of fifth thoracic vertebra.obj' , 
intervertebral_disk_of_first_lumbar_vertebra:'res/3d-objects/human/skeletal/intervertebral disk of first lumbar vertebra.obj' , 
intervertebral_disk_of_first_thoracic_vertebra:'res/3d-objects/human/skeletal/intervertebral disk of first thoracic vertebra.obj' , 
intervertebral_disk_of_fourth_cervical_vertebra:'res/3d-objects/human/skeletal/intervertebral disk of fourth cervical vertebra.obj' , 
intervertebral_disk_of_fourth_lumbar_vertebra:'res/3d-objects/human/skeletal/intervertebral disk of fourth lumbar vertebra.obj' , 
intervertebral_disk_of_fourth_thoracic_vertebra:'res/3d-objects/human/skeletal/intervertebral disk of fourth thoracic vertebra.obj' , 
intervertebral_disk_of_ninth_thoracic_vertebra:'res/3d-objects/human/skeletal/intervertebral disk of ninth thoracic vertebra.obj' , 
intervertebral_disk_of_second_lumbar_vertebra:'res/3d-objects/human/skeletal/intervertebral disk of second lumbar vertebra.obj' , 
intervertebral_disk_of_second_thoracic_vertebra:'res/3d-objects/human/skeletal/intervertebral disk of second thoracic vertebra.obj' , 
intervertebral_disk_of_seventh_cervical_vertebra:'res/3d-objects/human/skeletal/intervertebral disk of seventh cervical vertebra.obj' , 
intervertebral_disk_of_seventh_thoracic_vertebra:'res/3d-objects/human/skeletal/intervertebral disk of seventh thoracic vertebra.obj' , 
intervertebral_disk_of_sixth_cervical_vertebra:'res/3d-objects/human/skeletal/intervertebral disk of sixth cervical vertebra.obj' , 
intervertebral_disk_of_sixth_thoracic_vertebra:'res/3d-objects/human/skeletal/intervertebral disk of sixth thoracic vertebra.obj' , 
intervertebral_disk_of_tenth_thoracic_vertebra:'res/3d-objects/human/skeletal/intervertebral disk of tenth thoracic vertebra.obj' , 
intervertebral_disk_of_third_cervical_vertebra:'res/3d-objects/human/skeletal/intervertebral disk of third cervical vertebra.obj' , 
intervertebral_disk_of_third_lumbar_vertebra:'res/3d-objects/human/skeletal/intervertebral disk of third lumbar vertebra.obj' , 
intervertebral_disk_of_third_thoracic_vertebra:'res/3d-objects/human/skeletal/intervertebral disk of third thoracic vertebra.obj' , 
intervertebral_disk:'res/3d-objects/human/skeletal/intervertebral disk.obj' , 
left_calcaneus:'res/3d-objects/human/skeletal/left calcaneus.obj' , 
left_capitate:'res/3d-objects/human/skeletal/left capitate.obj' , 
left_clavicle:'res/3d-objects/human/skeletal/left clavicle.obj' , 
left_cuboid_bone:'res/3d-objects/human/skeletal/left cuboid bone.obj' , 
left_eighth_rib:'res/3d-objects/human/skeletal/left eighth rib.obj' , 
left_eleventh_rib:'res/3d-objects/human/skeletal/left eleventh rib.obj' , 
left_femur:'res/3d-objects/human/skeletal/left femur.obj' , 
left_fibula:'res/3d-objects/human/skeletal/left fibula.obj' , 
left_fifth_costal_cartilage:'res/3d-objects/human/skeletal/left fifth costal cartilage.obj' , 
left_fifth_metacarpal_bone:'res/3d-objects/human/skeletal/left fifth metacarpal bone.obj' , 
left_fifth_metatarsal_bone:'res/3d-objects/human/skeletal/left fifth metatarsal bone.obj' , 
left_fifth_rib:'res/3d-objects/human/skeletal/left fifth rib.obj' , 
left_first_costal_cartilage:'res/3d-objects/human/skeletal/left first costal cartilage.obj' , 
left_first_metacarpal_bone:'res/3d-objects/human/skeletal/left first metacarpal bone.obj' , 
left_first_metatarsal_bone:'res/3d-objects/human/skeletal/left first metatarsal bone.obj' , 
left_first_rib:'res/3d-objects/human/skeletal/left first rib.obj' , 
left_fourth_costal_cartilage:'res/3d-objects/human/skeletal/left fourth costal cartilage.obj' , 
left_fourth_metacarpal_bone:'res/3d-objects/human/skeletal/left fourth metacarpal bone.obj' , 
left_fourth_metatarsal_bone:'res/3d-objects/human/skeletal/left fourth metatarsal bone.obj' , 
left_fourth_rib:'res/3d-objects/human/skeletal/left fourth rib.obj' , 
left_hamate:'res/3d-objects/human/skeletal/left hamate.obj' , 
left_hip_bone:'res/3d-objects/human/skeletal/left hip bone.obj' , 
left_humerus:'res/3d-objects/human/skeletal/left humerus.obj' , 
left_inferior_nasal_concha:'res/3d-objects/human/skeletal/left inferior nasal concha.obj' , 
left_intermediate_cuneiform_bone:'res/3d-objects/human/skeletal/left intermediate cuneiform bone.obj' , 
left_lacrimal_bone:'res/3d-objects/human/skeletal/left lacrimal bone.obj' , 
left_lateral_cuneiform_bone:'res/3d-objects/human/skeletal/left lateral cuneiform bone.obj' , 
left_lateral_nasal_cartilage:'res/3d-objects/human/skeletal/left lateral nasal cartilage.obj' , 
left_lunate:'res/3d-objects/human/skeletal/left lunate.obj' , 
left_major_alar_cartilage:'res/3d-objects/human/skeletal/left major alar cartilage.obj' , 
left_maxilla:'res/3d-objects/human/skeletal/left maxilla.obj' , 
left_medial_cuneiform_bone:'res/3d-objects/human/skeletal/left medial cuneiform bone.obj' , 
left_nasal_bone:'res/3d-objects/human/skeletal/left nasal bone.obj' , 
left_ninth_rib:'res/3d-objects/human/skeletal/left ninth rib.obj' , 
left_palatine_bone:'res/3d-objects/human/skeletal/left palatine bone.obj' , 
left_parietal_bone:'res/3d-objects/human/skeletal/left parietal bone.obj' , 
left_patella:'res/3d-objects/human/skeletal/left patella.obj' , 
left_pisiform:'res/3d-objects/human/skeletal/left pisiform.obj' , 
left_radius:'res/3d-objects/human/skeletal/left radius.obj' , 
left_scaphoid:'res/3d-objects/human/skeletal/left scaphoid.obj' , 
left_scapula:'res/3d-objects/human/skeletal/left scapula.obj' , 
left_second_costal_cartilage:'res/3d-objects/human/skeletal/left second costal cartilage.obj' , 
left_second_metacarpal_bone:'res/3d-objects/human/skeletal/left second metacarpal bone.obj' , 
left_second_metatarsal_bone:'res/3d-objects/human/skeletal/left second metatarsal bone.obj' , 
left_second_rib:'res/3d-objects/human/skeletal/left second rib.obj' , 
left_seventh_costal_cartilage:'res/3d-objects/human/skeletal/left seventh costal cartilage.obj' , 
left_seventh_rib:'res/3d-objects/human/skeletal/left seventh rib.obj' , 
left_sixth_costal_cartilage:'res/3d-objects/human/skeletal/left sixth costal cartilage.obj' , 
left_sixth_rib:'res/3d-objects/human/skeletal/left sixth rib.obj' , 
left_talus:'res/3d-objects/human/skeletal/left talus.obj' , 
left_temporal_bone:'res/3d-objects/human/skeletal/left temporal bone.obj' , 
left_tenth_rib:'res/3d-objects/human/skeletal/left tenth rib.obj' , 
left_third_costal_cartilage:'res/3d-objects/human/skeletal/left third costal cartilage.obj' , 
left_third_metacarpal_bone:'res/3d-objects/human/skeletal/left third metacarpal bone.obj' , 
left_third_metatarsal_bone:'res/3d-objects/human/skeletal/left third metatarsal bone.obj' , 
left_third_rib:'res/3d-objects/human/skeletal/left third rib.obj' , 
left_tibia:'res/3d-objects/human/skeletal/left tibia.obj' , 
left_trapezium:'res/3d-objects/human/skeletal/left trapezium.obj' , 
left_trapezoid:'res/3d-objects/human/skeletal/left trapezoid.obj' , 
left_triquetral:'res/3d-objects/human/skeletal/left triquetral.obj' , 
left_twelfth_rib:'res/3d-objects/human/skeletal/left twelfth rib.obj' , 
left_ulna:'res/3d-objects/human/skeletal/left ulna.obj' , 
left_zygomatic_bone:'res/3d-objects/human/skeletal/left zygomatic bone.obj' , 
mandible:'res/3d-objects/human/skeletal/mandible.obj' , 
manubrium:'res/3d-objects/human/skeletal/manubrium.obj' , 
middle_phalanx_of_left_fourth_toe:'res/3d-objects/human/skeletal/middle phalanx of left fourth toe.obj' , 
middle_phalanx_of_left_index_finger:'res/3d-objects/human/skeletal/middle phalanx of left index finger.obj' , 
middle_phalanx_of_left_little_finger:'res/3d-objects/human/skeletal/middle phalanx of left little finger.obj' , 
middle_phalanx_of_left_little_toe:'res/3d-objects/human/skeletal/middle phalanx of left little toe.obj' , 
middle_phalanx_of_left_middle_finger:'res/3d-objects/human/skeletal/middle phalanx of left middle finger.obj' , 
middle_phalanx_of_left_ring_finger:'res/3d-objects/human/skeletal/middle phalanx of left ring finger.obj' , 
middle_phalanx_of_left_second_toe:'res/3d-objects/human/skeletal/middle phalanx of left second toe.obj' , 
middle_phalanx_of_left_third_toe:'res/3d-objects/human/skeletal/middle phalanx of left third toe.obj' , 
middle_phalanx_of_right_fourth_toe:'res/3d-objects/human/skeletal/middle phalanx of right fourth toe.obj' , 
middle_phalanx_of_right_index_finger:'res/3d-objects/human/skeletal/middle phalanx of right index finger.obj' , 
middle_phalanx_of_right_little_finger:'res/3d-objects/human/skeletal/middle phalanx of right little finger.obj' , 
middle_phalanx_of_right_little_toe:'res/3d-objects/human/skeletal/middle phalanx of right little toe.obj' , 
middle_phalanx_of_right_middle_finger:'res/3d-objects/human/skeletal/middle phalanx of right middle finger.obj' , 
middle_phalanx_of_right_ring_finger:'res/3d-objects/human/skeletal/middle phalanx of right ring finger.obj' , 
middle_phalanx_of_right_second_toe:'res/3d-objects/human/skeletal/middle phalanx of right second toe.obj' , 
middle_phalanx_of_right_third_toe:'res/3d-objects/human/skeletal/middle phalanx of right third toe.obj' , 
navicular_bone_of_left_foot:'res/3d-objects/human/skeletal/navicular bone of left foot.obj' , 
navicular_bone_of_right_foot:'res/3d-objects/human/skeletal/navicular bone of right foot.obj' , 
ninth_thoracic_vertebra:'res/3d-objects/human/skeletal/ninth thoracic vertebra.obj' , 
occipital_bone:'res/3d-objects/human/skeletal/occipital bone.obj' , 
parietal_bone:'res/3d-objects/human/skeletal/parietal bone.obj' , 
proximal_phalanx_of_index_finger:'res/3d-objects/human/skeletal/proximal phalanx of index finger.obj' , 
proximal_phalanx_of_left_big_toe:'res/3d-objects/human/skeletal/proximal phalanx of left big toe.obj' , 
proximal_phalanx_of_left_fourth_toe:'res/3d-objects/human/skeletal/proximal phalanx of left fourth toe.obj' , 
proximal_phalanx_of_left_little_toe:'res/3d-objects/human/skeletal/proximal phalanx of left little toe.obj' , 
proximal_phalanx_of_left_middle_finger:'res/3d-objects/human/skeletal/proximal phalanx of left middle finger.obj' , 
proximal_phalanx_of_left_second_toe:'res/3d-objects/human/skeletal/proximal phalanx of left second toe.obj' , 
proximal_phalanx_of_left_third_toe:'res/3d-objects/human/skeletal/proximal phalanx of left third toe.obj' , 
proximal_phalanx_of_little_finger:'res/3d-objects/human/skeletal/proximal phalanx of little finger.obj' , 
proximal_phalanx_of_right_big_toe:'res/3d-objects/human/skeletal/proximal phalanx of right big toe.obj' , 
proximal_phalanx_of_right_fourth_toe:'res/3d-objects/human/skeletal/proximal phalanx of right fourth toe.obj' , 
proximal_phalanx_of_right_index_finger:'res/3d-objects/human/skeletal/proximal phalanx of right index finger.obj' , 
proximal_phalanx_of_right_little_finger:'res/3d-objects/human/skeletal/proximal phalanx of right little finger.obj' , 
proximal_phalanx_of_right_little_toe:'res/3d-objects/human/skeletal/proximal phalanx of right little toe.obj' , 
proximal_phalanx_of_right_middle_finger:'res/3d-objects/human/skeletal/proximal phalanx of right middle finger.obj' , 
proximal_phalanx_of_right_ring_finger:'res/3d-objects/human/skeletal/proximal phalanx of right ring finger.obj' , 
proximal_phalanx_of_right_second_toe:'res/3d-objects/human/skeletal/proximal phalanx of right second toe.obj' , 
proximal_phalanx_of_right_third_toe:'res/3d-objects/human/skeletal/proximal phalanx of right third toe.obj' , 
proximal_phalanx_of_right_thumb:'res/3d-objects/human/skeletal/proximal phalanx of right thumb.obj' , 
proximal_phalanx_of_ring_finger:'res/3d-objects/human/skeletal/proximal phalanx of ring finger.obj' , 
proximal_phalanx_of_thumb:'res/3d-objects/human/skeletal/proximal phalanx of thumb.obj' , 
right_calcaneus:'res/3d-objects/human/skeletal/right calcaneus.obj' , 
right_capitate:'res/3d-objects/human/skeletal/right capitate.obj' , 
right_clavicle:'res/3d-objects/human/skeletal/right clavicle.obj' , 
right_cuboid_bone:'res/3d-objects/human/skeletal/right cuboid bone.obj' , 
right_eighth_rib:'res/3d-objects/human/skeletal/right eighth rib.obj' , 
right_eleventh_rib:'res/3d-objects/human/skeletal/right eleventh rib.obj' , 
right_femur:'res/3d-objects/human/skeletal/right femur.obj' , 
right_fibula:'res/3d-objects/human/skeletal/right fibula.obj' , 
right_fifth_costal_cartilage:'res/3d-objects/human/skeletal/right fifth costal cartilage.obj' , 
right_fifth_metacarpal_bone:'res/3d-objects/human/skeletal/right fifth metacarpal bone.obj' , 
right_fifth_metatarsal_bone:'res/3d-objects/human/skeletal/right fifth metatarsal bone.obj' , 
right_fifth_rib:'res/3d-objects/human/skeletal/right fifth rib.obj' , 
right_first_costal_cartilage:'res/3d-objects/human/skeletal/right first costal cartilage.obj' , 
right_first_metacarpal_bone:'res/3d-objects/human/skeletal/right first metacarpal bone.obj' , 
right_first_metatarsal_bone:'res/3d-objects/human/skeletal/right first metatarsal bone.obj' , 
right_first_rib:'res/3d-objects/human/skeletal/right first rib.obj' , 
right_fourth_costal_cartilage:'res/3d-objects/human/skeletal/right fourth costal cartilage.obj' , 
right_fourth_metacarpal_bone:'res/3d-objects/human/skeletal/right fourth metacarpal bone.obj' , 
right_fourth_metatarsal_bone:'res/3d-objects/human/skeletal/right fourth metatarsal bone.obj' , 
right_fourth_rib:'res/3d-objects/human/skeletal/right fourth rib.obj' , 
right_hamate:'res/3d-objects/human/skeletal/right hamate.obj' , 
right_hip_bone:'res/3d-objects/human/skeletal/right hip bone.obj' , 
right_humerus:'res/3d-objects/human/skeletal/right humerus.obj' , 
right_inferior_nasal_concha:'res/3d-objects/human/skeletal/right inferior nasal concha.obj' , 
right_intermediate_cuneiform_bone:'res/3d-objects/human/skeletal/right intermediate cuneiform bone.obj' , 
right_lacrimal_bone:'res/3d-objects/human/skeletal/right lacrimal bone.obj' , 
right_lateral_cuneiform_bone:'res/3d-objects/human/skeletal/right lateral cuneiform bone.obj' , 
right_lateral_nasal_cartilage:'res/3d-objects/human/skeletal/right lateral nasal cartilage.obj' , 
right_lunate:'res/3d-objects/human/skeletal/right lunate.obj' , 
right_major_alar_cartilage:'res/3d-objects/human/skeletal/right major alar cartilage.obj' , 
right_maxilla:'res/3d-objects/human/skeletal/right maxilla.obj' , 
right_medial_cuneiform_bone:'res/3d-objects/human/skeletal/right medial cuneiform bone.obj' , 
right_nasal_bone:'res/3d-objects/human/skeletal/right nasal bone.obj' , 
right_ninth_rib:'res/3d-objects/human/skeletal/right ninth rib.obj' , 
right_palatine_bone:'res/3d-objects/human/skeletal/right palatine bone.obj' , 
right_parietal_bone:'res/3d-objects/human/skeletal/right parietal bone.obj' , 
right_patella:'res/3d-objects/human/skeletal/right patella.obj' , 
right_pisiform:'res/3d-objects/human/skeletal/right pisiform.obj' , 
right_radius:'res/3d-objects/human/skeletal/right radius.obj' , 
right_scaphoid:'res/3d-objects/human/skeletal/right scaphoid.obj' , 
right_scapula:'res/3d-objects/human/skeletal/right scapula.obj' , 
right_second_costal_cartilage:'res/3d-objects/human/skeletal/right second costal cartilage.obj' , 
right_second_metacarpal_bone:'res/3d-objects/human/skeletal/right second metacarpal bone.obj' , 
right_second_metatarsal_bone:'res/3d-objects/human/skeletal/right second metatarsal bone.obj' , 
right_second_rib:'res/3d-objects/human/skeletal/right second rib.obj' , 
right_seventh_costal_cartilage:'res/3d-objects/human/skeletal/right seventh costal cartilage.obj' , 
right_seventh_rib:'res/3d-objects/human/skeletal/right seventh rib.obj' , 
right_sixth_costal_cartilage:'res/3d-objects/human/skeletal/right sixth costal cartilage.obj' , 
right_sixth_rib:'res/3d-objects/human/skeletal/right sixth rib.obj' , 
right_talus:'res/3d-objects/human/skeletal/right talus.obj' , 
right_temporal_bone:'res/3d-objects/human/skeletal/right temporal bone.obj' , 
right_tenth_rib:'res/3d-objects/human/skeletal/right tenth rib.obj' , 
right_third_costal_cartilage:'res/3d-objects/human/skeletal/right third costal cartilage.obj' , 
right_third_metacarpal_bone:'res/3d-objects/human/skeletal/right third metacarpal bone.obj' , 
right_third_metatarsal_bone:'res/3d-objects/human/skeletal/right third metatarsal bone.obj' , 
right_third_rib:'res/3d-objects/human/skeletal/right third rib.obj' , 
right_tibia:'res/3d-objects/human/skeletal/right tibia.obj' , 
right_trapezium:'res/3d-objects/human/skeletal/right trapezium.obj' , 
right_trapezoid:'res/3d-objects/human/skeletal/right trapezoid.obj' , 
right_triquetral:'res/3d-objects/human/skeletal/right triquetral.obj' , 
right_twelfth_rib:'res/3d-objects/human/skeletal/right twelfth rib.obj' , 
right_ulna:'res/3d-objects/human/skeletal/right ulna.obj' , 
right_zygomatic_bone:'res/3d-objects/human/skeletal/right zygomatic bone.obj' , 
sacrum:'res/3d-objects/human/skeletal/sacrum.obj' , 
second_lumbar_vertebra:'res/3d-objects/human/skeletal/second lumbar vertebra.obj' , 
second_thoracic_vertebra:'res/3d-objects/human/skeletal/second thoracic vertebra.obj' , 
septal_nasal_cartilage:'res/3d-objects/human/skeletal/septal nasal cartilage.obj' , 
sesamoid_bone_of_foot_1:'res/3d-objects/human/skeletal/sesamoid bone of foot 1.obj' , 
sesamoid_bone_of_foot_2:'res/3d-objects/human/skeletal/sesamoid bone of foot 2.obj' , 
sesamoid_bone_of_foot_3:'res/3d-objects/human/skeletal/sesamoid bone of foot 3.obj' , 
sesamoid_bone_of_foot:'res/3d-objects/human/skeletal/sesamoid bone of foot.obj' , 
seventh_cervical_vertebra:'res/3d-objects/human/skeletal/seventh cervical vertebra.obj' , 
seventh_thoracic_vertebra:'res/3d-objects/human/skeletal/seventh thoracic vertebra.obj' , 
sixth_cervical_vertebra:'res/3d-objects/human/skeletal/sixth cervical vertebra.obj' , 
sixth_thoracic_vertebra:'res/3d-objects/human/skeletal/sixth thoracic vertebra.obj' , 
sphenoid_bone:'res/3d-objects/human/skeletal/sphenoid bone.obj' , 
tenth_thoracic_vertebra:'res/3d-objects/human/skeletal/tenth thoracic vertebra.obj' , 
third_cervical_vertebra:'res/3d-objects/human/skeletal/third cervical vertebra.obj' , 
third_lumbar_vertebra:'res/3d-objects/human/skeletal/third lumbar vertebra.obj' , 
third_thoracic_vertebra:'res/3d-objects/human/skeletal/third thoracic vertebra.obj' , 
tooth:'res/3d-objects/human/skeletal/tooth.obj' , 
tooth_1:'res/3d-objects/human/skeletal/tooth_1.obj' , 
tooth_10:'res/3d-objects/human/skeletal/tooth_10.obj' , 
tooth_11:'res/3d-objects/human/skeletal/tooth_11.obj' , 
tooth_12:'res/3d-objects/human/skeletal/tooth_12.obj' , 
tooth_13:'res/3d-objects/human/skeletal/tooth_13.obj' , 
tooth_14:'res/3d-objects/human/skeletal/tooth_14.obj' , 
tooth_15:'res/3d-objects/human/skeletal/tooth_15.obj' , 
tooth_16:'res/3d-objects/human/skeletal/tooth_16.obj' , 
tooth_17:'res/3d-objects/human/skeletal/tooth_17.obj' , 
tooth_18:'res/3d-objects/human/skeletal/tooth_18.obj' , 
tooth_19:'res/3d-objects/human/skeletal/tooth_19.obj' , 
tooth_2:'res/3d-objects/human/skeletal/tooth_2.obj' , 
tooth_20:'res/3d-objects/human/skeletal/tooth_20.obj' , 
tooth_21:'res/3d-objects/human/skeletal/tooth_21.obj' , 
tooth_22:'res/3d-objects/human/skeletal/tooth_22.obj' , 
tooth_23:'res/3d-objects/human/skeletal/tooth_23.obj' , 
tooth_24:'res/3d-objects/human/skeletal/tooth_24.obj' , 
tooth_25:'res/3d-objects/human/skeletal/tooth_25.obj' , 
tooth_26:'res/3d-objects/human/skeletal/tooth_26.obj' , 
tooth_27:'res/3d-objects/human/skeletal/tooth_27.obj' , 
tooth_3:'res/3d-objects/human/skeletal/tooth_3.obj' , 
tooth_4:'res/3d-objects/human/skeletal/tooth_4.obj' , 
tooth_5:'res/3d-objects/human/skeletal/tooth_5.obj' , 
tooth_6:'res/3d-objects/human/skeletal/tooth_6.obj' , 
tooth_7:'res/3d-objects/human/skeletal/tooth_7.obj' , 
tooth_8:'res/3d-objects/human/skeletal/tooth_8.obj' , 
tooth_9:'res/3d-objects/human/skeletal/tooth_9.obj' , 
twelfth_thoracic_vertebra:'res/3d-objects/human/skeletal/twelfth thoracic vertebra.obj' , 
vomer:'res/3d-objects/human/skeletal/vomer.obj' , 
xiphoid_process:'res/3d-objects/human/skeletal/xiphoid process.obj' , 
 };  