/** ojsa */

var prefiks = 'skeletal';

var skeletalMap = {
  atlas: `res/3d-objects/human/${prefiks}/atlas.obj`,
  axis: `res/3d-objects/human/${prefiks}/axis.obj`,
  body_of_sternum: `res/3d-objects/human/${prefiks}/body of sternum.obj`,
  distal_phalanx_of_left_big_toe: `res/3d-objects/human/${prefiks}/distal phalanx of left big toe.obj`,
  distal_phalanx_of_left_fourth_toe: `res/3d-objects/human/${prefiks}/distal phalanx of left fourth toe.obj`,
  distal_phalanx_of_left_index_finger: `res/3d-objects/human/${prefiks}/distal phalanx of left index finger.obj`,
  distal_phalanx_of_left_little_finger: `res/3d-objects/human/${prefiks}/distal phalanx of left little finger.obj`,
  distal_phalanx_of_left_little_toe: `res/3d-objects/human/${prefiks}/distal phalanx of left little toe.obj`,
  distal_phalanx_of_left_middle_finger: `res/3d-objects/human/${prefiks}/distal phalanx of left middle finger.obj`,
  distal_phalanx_of_left_ring_finger: `res/3d-objects/human/${prefiks}/distal phalanx of left ring finger.obj`,
  distal_phalanx_of_left_second_toe: `res/3d-objects/human/${prefiks}/distal phalanx of left second toe.obj`,
  distal_phalanx_of_left_third_toe: `res/3d-objects/human/${prefiks}/distal phalanx of left third toe.obj`,
  distal_phalanx_of_left_thumb: `res/3d-objects/human/${prefiks}/distal phalanx of left thumb.obj`,
  distal_phalanx_of_right_big_toe: `res/3d-objects/human/${prefiks}/distal phalanx of right big toe.obj`,
  distal_phalanx_of_right_fourth_toe: `res/3d-objects/human/${prefiks}/distal phalanx of right fourth toe.obj`,
  distal_phalanx_of_right_index_finger: `res/3d-objects/human/${prefiks}/distal phalanx of right index finger.obj`,
  distal_phalanx_of_right_little_finger: `res/3d-objects/human/${prefiks}/distal phalanx of right little finger.obj`,
  distal_phalanx_of_right_little_toe: `res/3d-objects/human/${prefiks}/distal phalanx of right little toe.obj`,
  distal_phalanx_of_right_middle_finger: `res/3d-objects/human/${prefiks}/distal phalanx of right middle finger.obj`,
  distal_phalanx_of_right_ring_finger: `res/3d-objects/human/${prefiks}/distal phalanx of right ring finger.obj`,
  distal_phalanx_of_right_second_toe: `res/3d-objects/human/${prefiks}/distal phalanx of right second toe.obj`,
  distal_phalanx_of_right_third_toe: `res/3d-objects/human/${prefiks}/distal phalanx of right third toe.obj`,
  distal_phalanx_of_right_thumb: `res/3d-objects/human/${prefiks}/distal phalanx of right thumb.obj`,
  eighth_thoracic_vertebra: `res/3d-objects/human/${prefiks}/eighth thoracic vertebra.obj`,
  eleventh_thoracic_vertebra: `res/3d-objects/human/${prefiks}/eleventh thoracic vertebra.obj`,
  ethmoid: `res/3d-objects/human/${prefiks}/ethmoid.obj`,
  fifth_cervical_vertebra: `res/3d-objects/human/${prefiks}/fifth cervical vertebra.obj`,
  fifth_lumbar_vertebra: `res/3d-objects/human/${prefiks}/fifth lumbar vertebra.obj`,
  fifth_thoracic_vertebra: `res/3d-objects/human/${prefiks}/fifth thoracic vertebra.obj`,
  first_lumbar_vertebra: `res/3d-objects/human/${prefiks}/first lumbar vertebra.obj`,
  first_thoracic_vertebra: `res/3d-objects/human/${prefiks}/first thoracic vertebra.obj`,
  flexor_retinaculum_of_left_wrist: `res/3d-objects/human/${prefiks}/flexor retinaculum of left wrist.obj`,
  flexor_retinaculum_of_right_wrist: `res/3d-objects/human/${prefiks}/flexor retinaculum of right wrist.obj`,
  fourth_cervical_vertebra: `res/3d-objects/human/${prefiks}/fourth cervical vertebra.obj`,
  fourth_lumbar_vertebra: `res/3d-objects/human/${prefiks}/fourth lumbar vertebra.obj`,
  fourth_thoracic_vertebra: `res/3d-objects/human/${prefiks}/fourth thoracic vertebra.obj`,
  frontal_bone: `res/3d-objects/human/${prefiks}/frontal bone.obj`,
  hyoid_bone: `res/3d-objects/human/${prefiks}/hyoid bone.obj`,
  hyoid_bone2: `res/3d-objects/human/${prefiks}/hyoid bone2.obj`,
  intervertebral_disk_of_axis: `res/3d-objects/human/${prefiks}/intervertebral disk of axis.obj`,
  intervertebral_disk_of_eighth_thoracic_vertebra: `res/3d-objects/human/${prefiks}/intervertebral disk of eighth thoracic vertebra.obj`,
  intervertebral_disk_of_eleventh_thoracic_vertebra: `res/3d-objects/human/${prefiks}/intervertebral disk of eleventh thoracic vertebra.obj`,
  intervertebral_disk_of_fifth_cervical_vertebra: `res/3d-objects/human/${prefiks}/intervertebral disk of fifth cervical vertebra.obj`,
  intervertebral_disk_of_fifth_lumbar_vertebra: `res/3d-objects/human/${prefiks}/intervertebral disk of fifth lumbar vertebra.obj`,
  intervertebral_disk_of_fifth_thoracic_vertebra: `res/3d-objects/human/${prefiks}/intervertebral disk of fifth thoracic vertebra.obj`,
  intervertebral_disk_of_first_lumbar_vertebra: `res/3d-objects/human/${prefiks}/intervertebral disk of first lumbar vertebra.obj`,
  intervertebral_disk_of_first_thoracic_vertebra: `res/3d-objects/human/${prefiks}/intervertebral disk of first thoracic vertebra.obj`,
  intervertebral_disk_of_fourth_cervical_vertebra: `res/3d-objects/human/${prefiks}/intervertebral disk of fourth cervical vertebra.obj`,
  intervertebral_disk_of_fourth_lumbar_vertebra: `res/3d-objects/human/${prefiks}/intervertebral disk of fourth lumbar vertebra.obj`,
  intervertebral_disk_of_fourth_thoracic_vertebra: `res/3d-objects/human/${prefiks}/intervertebral disk of fourth thoracic vertebra.obj`,
  intervertebral_disk_of_ninth_thoracic_vertebra: `res/3d-objects/human/${prefiks}/intervertebral disk of ninth thoracic vertebra.obj`,
  intervertebral_disk_of_second_lumbar_vertebra: `res/3d-objects/human/${prefiks}/intervertebral disk of second lumbar vertebra.obj`,
  intervertebral_disk_of_second_thoracic_vertebra: `res/3d-objects/human/${prefiks}/intervertebral disk of second thoracic vertebra.obj`,
  intervertebral_disk_of_seventh_cervical_vertebra: `res/3d-objects/human/${prefiks}/intervertebral disk of seventh cervical vertebra.obj`,
  intervertebral_disk_of_seventh_thoracic_vertebra: `res/3d-objects/human/${prefiks}/intervertebral disk of seventh thoracic vertebra.obj`,
  intervertebral_disk_of_sixth_cervical_vertebra: `res/3d-objects/human/${prefiks}/intervertebral disk of sixth cervical vertebra.obj`,
  intervertebral_disk_of_sixth_thoracic_vertebra: `res/3d-objects/human/${prefiks}/intervertebral disk of sixth thoracic vertebra.obj`,
  intervertebral_disk_of_tenth_thoracic_vertebra: `res/3d-objects/human/${prefiks}/intervertebral disk of tenth thoracic vertebra.obj`,
  intervertebral_disk_of_third_cervical_vertebra: `res/3d-objects/human/${prefiks}/intervertebral disk of third cervical vertebra.obj`,
  intervertebral_disk_of_third_lumbar_vertebra: `res/3d-objects/human/${prefiks}/intervertebral disk of third lumbar vertebra.obj`,
  intervertebral_disk_of_third_thoracic_vertebra: `res/3d-objects/human/${prefiks}/intervertebral disk of third thoracic vertebra.obj`,
  intervertebral_disk: `res/3d-objects/human/${prefiks}/intervertebral disk.obj`,
  left_calcaneus: `res/3d-objects/human/${prefiks}/left calcaneus.obj`,
  left_capitate: `res/3d-objects/human/${prefiks}/left capitate.obj`,
  left_clavicle: `res/3d-objects/human/${prefiks}/left clavicle.obj`,
  left_cuboid_bone: `res/3d-objects/human/${prefiks}/left cuboid bone.obj`,
  left_eighth_rib: `res/3d-objects/human/${prefiks}/left eighth rib.obj`,
  left_eleventh_rib: `res/3d-objects/human/${prefiks}/left eleventh rib.obj`,
  left_femur: `res/3d-objects/human/${prefiks}/left femur.obj`,
  left_fibula: `res/3d-objects/human/${prefiks}/left fibula.obj`,
  left_fifth_costal_cartilage: `res/3d-objects/human/${prefiks}/left fifth costal cartilage.obj`,
  left_fifth_metacarpal_bone: `res/3d-objects/human/${prefiks}/left fifth metacarpal bone.obj`,
  left_fifth_metatarsal_bone: `res/3d-objects/human/${prefiks}/left fifth metatarsal bone.obj`,
  left_fifth_rib: `res/3d-objects/human/${prefiks}/left fifth rib.obj`,
  left_first_costal_cartilage: `res/3d-objects/human/${prefiks}/left first costal cartilage.obj`,
  left_first_metacarpal_bone: `res/3d-objects/human/${prefiks}/left first metacarpal bone.obj`,
  left_first_metatarsal_bone: `res/3d-objects/human/${prefiks}/left first metatarsal bone.obj`,
  left_first_rib: `res/3d-objects/human/${prefiks}/left first rib.obj`,
  left_fourth_costal_cartilage: `res/3d-objects/human/${prefiks}/left fourth costal cartilage.obj`,
  left_fourth_metacarpal_bone: `res/3d-objects/human/${prefiks}/left fourth metacarpal bone.obj`,
  left_fourth_metatarsal_bone: `res/3d-objects/human/${prefiks}/left fourth metatarsal bone.obj`,
  left_fourth_rib: `res/3d-objects/human/${prefiks}/left fourth rib.obj`,
  left_hamate: `res/3d-objects/human/${prefiks}/left hamate.obj`,
  left_hip_bone: `res/3d-objects/human/${prefiks}/left hip bone.obj`,
  left_humerus: `res/3d-objects/human/${prefiks}/left humerus.obj`,
  left_inferior_nasal_concha: `res/3d-objects/human/${prefiks}/left inferior nasal concha.obj`,
  left_intermediate_cuneiform_bone: `res/3d-objects/human/${prefiks}/left intermediate cuneiform bone.obj`,
  left_lacrimal_bone: `res/3d-objects/human/${prefiks}/left lacrimal bone.obj`,
  left_lateral_cuneiform_bone: `res/3d-objects/human/${prefiks}/left lateral cuneiform bone.obj`,
  left_lateral_nasal_cartilage: `res/3d-objects/human/${prefiks}/left lateral nasal cartilage.obj`,
  left_lunate: `res/3d-objects/human/${prefiks}/left lunate.obj`,
  left_major_alar_cartilage: `res/3d-objects/human/${prefiks}/left major alar cartilage.obj`,
  left_maxilla: `res/3d-objects/human/${prefiks}/left maxilla.obj`,
  left_medial_cuneiform_bone: `res/3d-objects/human/${prefiks}/left medial cuneiform bone.obj`,
  left_nasal_bone: `res/3d-objects/human/${prefiks}/left nasal bone.obj`,
  left_ninth_rib: `res/3d-objects/human/${prefiks}/left ninth rib.obj`,
  left_palatine_bone: `res/3d-objects/human/${prefiks}/left palatine bone.obj`,
  left_parietal_bone: `res/3d-objects/human/${prefiks}/left parietal bone.obj`,
  left_patella: `res/3d-objects/human/${prefiks}/left patella.obj`,
  left_pisiform: `res/3d-objects/human/${prefiks}/left pisiform.obj`,
  left_radius: `res/3d-objects/human/${prefiks}/left radius.obj`,
  left_scaphoid: `res/3d-objects/human/${prefiks}/left scaphoid.obj`,
  left_scapula: `res/3d-objects/human/${prefiks}/left scapula.obj`,
  left_second_costal_cartilage: `res/3d-objects/human/${prefiks}/left second costal cartilage.obj`,
  left_second_metacarpal_bone: `res/3d-objects/human/${prefiks}/left second metacarpal bone.obj`,
  left_second_metatarsal_bone: `res/3d-objects/human/${prefiks}/left second metatarsal bone.obj`,
  left_second_rib: `res/3d-objects/human/${prefiks}/left second rib.obj`,
  left_seventh_costal_cartilage: `res/3d-objects/human/${prefiks}/left seventh costal cartilage.obj`,
  left_seventh_rib: `res/3d-objects/human/${prefiks}/left seventh rib.obj`,
  left_sixth_costal_cartilage: `res/3d-objects/human/${prefiks}/left sixth costal cartilage.obj`,
  left_sixth_rib: `res/3d-objects/human/${prefiks}/left sixth rib.obj`,
  left_talus: `res/3d-objects/human/${prefiks}/left talus.obj`,
  left_temporal_bone: `res/3d-objects/human/${prefiks}/left temporal bone.obj`,
  left_tenth_rib: `res/3d-objects/human/${prefiks}/left tenth rib.obj`,
  left_third_costal_cartilage: `res/3d-objects/human/${prefiks}/left third costal cartilage.obj`,
  left_third_metacarpal_bone: `res/3d-objects/human/${prefiks}/left third metacarpal bone.obj`,
  left_third_metatarsal_bone: `res/3d-objects/human/${prefiks}/left third metatarsal bone.obj`,
  left_third_rib: `res/3d-objects/human/${prefiks}/left third rib.obj`,
  left_tibia: `res/3d-objects/human/${prefiks}/left tibia.obj`,
  left_trapezium: `res/3d-objects/human/${prefiks}/left trapezium.obj`,
  left_trapezoid: `res/3d-objects/human/${prefiks}/left trapezoid.obj`,
  left_triquetral: `res/3d-objects/human/${prefiks}/left triquetral.obj`,
  left_twelfth_rib: `res/3d-objects/human/${prefiks}/left twelfth rib.obj`,
  left_ulna: `res/3d-objects/human/${prefiks}/left ulna.obj`,
  left_zygomatic_bone: `res/3d-objects/human/${prefiks}/left zygomatic bone.obj`,
  mandible: `res/3d-objects/human/${prefiks}/mandible.obj`,
  manubrium: `res/3d-objects/human/${prefiks}/manubrium.obj`,
  middle_phalanx_of_left_fourth_toe: `res/3d-objects/human/${prefiks}/middle phalanx of left fourth toe.obj`,
  middle_phalanx_of_left_index_finger: `res/3d-objects/human/${prefiks}/middle phalanx of left index finger.obj`,
  middle_phalanx_of_left_little_finger: `res/3d-objects/human/${prefiks}/middle phalanx of left little finger.obj`,
  middle_phalanx_of_left_little_toe: `res/3d-objects/human/${prefiks}/middle phalanx of left little toe.obj`,
  middle_phalanx_of_left_middle_finger: `res/3d-objects/human/${prefiks}/middle phalanx of left middle finger.obj`,
  middle_phalanx_of_left_ring_finger: `res/3d-objects/human/${prefiks}/middle phalanx of left ring finger.obj`,
  middle_phalanx_of_left_second_toe: `res/3d-objects/human/${prefiks}/middle phalanx of left second toe.obj`,
  middle_phalanx_of_left_third_toe: `res/3d-objects/human/${prefiks}/middle phalanx of left third toe.obj`,
  middle_phalanx_of_right_fourth_toe: `res/3d-objects/human/${prefiks}/middle phalanx of right fourth toe.obj`,
  middle_phalanx_of_right_index_finger: `res/3d-objects/human/${prefiks}/middle phalanx of right index finger.obj`,
  middle_phalanx_of_right_little_finger: `res/3d-objects/human/${prefiks}/middle phalanx of right little finger.obj`,
  middle_phalanx_of_right_little_toe: `res/3d-objects/human/${prefiks}/middle phalanx of right little toe.obj`,
  middle_phalanx_of_right_middle_finger: `res/3d-objects/human/${prefiks}/middle phalanx of right middle finger.obj`,
  middle_phalanx_of_right_ring_finger: `res/3d-objects/human/${prefiks}/middle phalanx of right ring finger.obj`,
  middle_phalanx_of_right_second_toe: `res/3d-objects/human/${prefiks}/middle phalanx of right second toe.obj`,
  middle_phalanx_of_right_third_toe: `res/3d-objects/human/${prefiks}/middle phalanx of right third toe.obj`,
  navicular_bone_of_left_foot: `res/3d-objects/human/${prefiks}/navicular bone of left foot.obj`,
  navicular_bone_of_right_foot: `res/3d-objects/human/${prefiks}/navicular bone of right foot.obj`,
  ninth_thoracic_vertebra: `res/3d-objects/human/${prefiks}/ninth thoracic vertebra.obj`,
  occipital_bone: `res/3d-objects/human/${prefiks}/occipital bone.obj`,
  parietal_bone: `res/3d-objects/human/${prefiks}/parietal bone.obj`,
  proximal_phalanx_of_index_finger: `res/3d-objects/human/${prefiks}/proximal phalanx of index finger.obj`,
  proximal_phalanx_of_left_big_toe: `res/3d-objects/human/${prefiks}/proximal phalanx of left big toe.obj`,
  proximal_phalanx_of_left_fourth_toe: `res/3d-objects/human/${prefiks}/proximal phalanx of left fourth toe.obj`,
  proximal_phalanx_of_left_little_toe: `res/3d-objects/human/${prefiks}/proximal phalanx of left little toe.obj`,
  proximal_phalanx_of_left_middle_finger: `res/3d-objects/human/${prefiks}/proximal phalanx of left middle finger.obj`,
  proximal_phalanx_of_left_second_toe: `res/3d-objects/human/${prefiks}/proximal phalanx of left second toe.obj`,
  proximal_phalanx_of_left_third_toe: `res/3d-objects/human/${prefiks}/proximal phalanx of left third toe.obj`,
  proximal_phalanx_of_little_finger: `res/3d-objects/human/${prefiks}/proximal phalanx of little finger.obj`,
  proximal_phalanx_of_right_big_toe: `res/3d-objects/human/${prefiks}/proximal phalanx of right big toe.obj`,
  proximal_phalanx_of_right_fourth_toe: `res/3d-objects/human/${prefiks}/proximal phalanx of right fourth toe.obj`,
  proximal_phalanx_of_right_index_finger: `res/3d-objects/human/${prefiks}/proximal phalanx of right index finger.obj`,
  proximal_phalanx_of_right_little_finger: `res/3d-objects/human/${prefiks}/proximal phalanx of right little finger.obj`,
  proximal_phalanx_of_right_little_toe: `res/3d-objects/human/${prefiks}/proximal phalanx of right little toe.obj`,
  proximal_phalanx_of_right_middle_finger: `res/3d-objects/human/${prefiks}/proximal phalanx of right middle finger.obj`,
  proximal_phalanx_of_right_ring_finger: `res/3d-objects/human/${prefiks}/proximal phalanx of right ring finger.obj`,
  proximal_phalanx_of_right_second_toe: `res/3d-objects/human/${prefiks}/proximal phalanx of right second toe.obj`,
  proximal_phalanx_of_right_third_toe: `res/3d-objects/human/${prefiks}/proximal phalanx of right third toe.obj`,
  proximal_phalanx_of_right_thumb: `res/3d-objects/human/${prefiks}/proximal phalanx of right thumb.obj`,
  proximal_phalanx_of_ring_finger: `res/3d-objects/human/${prefiks}/proximal phalanx of ring finger.obj`,
  proximal_phalanx_of_thumb: `res/3d-objects/human/${prefiks}/proximal phalanx of thumb.obj`,
  right_calcaneus: `res/3d-objects/human/${prefiks}/right calcaneus.obj`,
  right_capitate: `res/3d-objects/human/${prefiks}/right capitate.obj`,
  right_clavicle: `res/3d-objects/human/${prefiks}/right clavicle.obj`,
  right_cuboid_bone: `res/3d-objects/human/${prefiks}/right cuboid bone.obj`,
  right_eighth_rib: `res/3d-objects/human/${prefiks}/right eighth rib.obj`,
  right_eleventh_rib: `res/3d-objects/human/${prefiks}/right eleventh rib.obj`,
  right_femur: `res/3d-objects/human/${prefiks}/right femur.obj`,
  right_fibula: `res/3d-objects/human/${prefiks}/right fibula.obj`,
  right_fifth_costal_cartilage: `res/3d-objects/human/${prefiks}/right fifth costal cartilage.obj`,
  right_fifth_metacarpal_bone: `res/3d-objects/human/${prefiks}/right fifth metacarpal bone.obj`,
  right_fifth_metatarsal_bone: `res/3d-objects/human/${prefiks}/right fifth metatarsal bone.obj`,
  right_fifth_rib: `res/3d-objects/human/${prefiks}/right fifth rib.obj`,
  right_first_costal_cartilage: `res/3d-objects/human/${prefiks}/right first costal cartilage.obj`,
  right_first_metacarpal_bone: `res/3d-objects/human/${prefiks}/right first metacarpal bone.obj`,
  right_first_metatarsal_bone: `res/3d-objects/human/${prefiks}/right first metatarsal bone.obj`,
  right_first_rib: `res/3d-objects/human/${prefiks}/right first rib.obj`,
  right_fourth_costal_cartilage: `res/3d-objects/human/${prefiks}/right fourth costal cartilage.obj`,
  right_fourth_metacarpal_bone: `res/3d-objects/human/${prefiks}/right fourth metacarpal bone.obj`,
  right_fourth_metatarsal_bone: `res/3d-objects/human/${prefiks}/right fourth metatarsal bone.obj`,
  right_fourth_rib: `res/3d-objects/human/${prefiks}/right fourth rib.obj`,
  right_hamate: `res/3d-objects/human/${prefiks}/right hamate.obj`,
  right_hip_bone: `res/3d-objects/human/${prefiks}/right hip bone.obj`,
  right_humerus: `res/3d-objects/human/${prefiks}/right humerus.obj`,
  right_inferior_nasal_concha: `res/3d-objects/human/${prefiks}/right inferior nasal concha.obj`,
  right_intermediate_cuneiform_bone: `res/3d-objects/human/${prefiks}/right intermediate cuneiform bone.obj`,
  right_lacrimal_bone: `res/3d-objects/human/${prefiks}/right lacrimal bone.obj`,
  right_lateral_cuneiform_bone: `res/3d-objects/human/${prefiks}/right lateral cuneiform bone.obj`,
  right_lateral_nasal_cartilage: `res/3d-objects/human/${prefiks}/right lateral nasal cartilage.obj`,
  right_lunate: `res/3d-objects/human/${prefiks}/right lunate.obj`,
  right_major_alar_cartilage: `res/3d-objects/human/${prefiks}/right major alar cartilage.obj`,
  right_maxilla: `res/3d-objects/human/${prefiks}/right maxilla.obj`,
  right_medial_cuneiform_bone: `res/3d-objects/human/${prefiks}/right medial cuneiform bone.obj`,
  right_nasal_bone: `res/3d-objects/human/${prefiks}/right nasal bone.obj`,
  right_ninth_rib: `res/3d-objects/human/${prefiks}/right ninth rib.obj`,
  right_palatine_bone: `res/3d-objects/human/${prefiks}/right palatine bone.obj`,
  right_parietal_bone: `res/3d-objects/human/${prefiks}/right parietal bone.obj`,
  right_patella: `res/3d-objects/human/${prefiks}/right patella.obj`,
  right_pisiform: `res/3d-objects/human/${prefiks}/right pisiform.obj`,
  right_radius: `res/3d-objects/human/${prefiks}/right radius.obj`,
  right_scaphoid: `res/3d-objects/human/${prefiks}/right scaphoid.obj`,
  right_scapula: `res/3d-objects/human/${prefiks}/right scapula.obj`,
  right_second_costal_cartilage: `res/3d-objects/human/${prefiks}/right second costal cartilage.obj`,
  right_second_metacarpal_bone: `res/3d-objects/human/${prefiks}/right second metacarpal bone.obj`,
  right_second_metatarsal_bone: `res/3d-objects/human/${prefiks}/right second metatarsal bone.obj`,
  right_second_rib: `res/3d-objects/human/${prefiks}/right second rib.obj`,
  right_seventh_costal_cartilage: `res/3d-objects/human/${prefiks}/right seventh costal cartilage.obj`,
  right_seventh_rib: `res/3d-objects/human/${prefiks}/right seventh rib.obj`,
  right_sixth_costal_cartilage: `res/3d-objects/human/${prefiks}/right sixth costal cartilage.obj`,
  right_sixth_rib: `res/3d-objects/human/${prefiks}/right sixth rib.obj`,
  right_talus: `res/3d-objects/human/${prefiks}/right talus.obj`,
  right_temporal_bone: `res/3d-objects/human/${prefiks}/right temporal bone.obj`,
  right_tenth_rib: `res/3d-objects/human/${prefiks}/right tenth rib.obj`,
  right_third_costal_cartilage: `res/3d-objects/human/${prefiks}/right third costal cartilage.obj`,
  right_third_metacarpal_bone: `res/3d-objects/human/${prefiks}/right third metacarpal bone.obj`,
  right_third_metatarsal_bone: `res/3d-objects/human/${prefiks}/right third metatarsal bone.obj`,
  right_third_rib: `res/3d-objects/human/${prefiks}/right third rib.obj`,
  right_tibia: `res/3d-objects/human/${prefiks}/right tibia.obj`,
  right_trapezium: `res/3d-objects/human/${prefiks}/right trapezium.obj`,
  right_trapezoid: `res/3d-objects/human/${prefiks}/right trapezoid.obj`,
  right_triquetral: `res/3d-objects/human/${prefiks}/right triquetral.obj`,
  right_twelfth_rib: `res/3d-objects/human/${prefiks}/right twelfth rib.obj`,
  right_ulna: `res/3d-objects/human/${prefiks}/right ulna.obj`,
  right_zygomatic_bone: `res/3d-objects/human/${prefiks}/right zygomatic bone.obj`,
  sacrum: `res/3d-objects/human/${prefiks}/sacrum.obj`,
  second_lumbar_vertebra: `res/3d-objects/human/${prefiks}/second lumbar vertebra.obj`,
  second_thoracic_vertebra: `res/3d-objects/human/${prefiks}/second thoracic vertebra.obj`,
  septal_nasal_cartilage: `res/3d-objects/human/${prefiks}/septal nasal cartilage.obj`,
  sesamoid_bone_of_foot_1: `res/3d-objects/human/${prefiks}/sesamoid bone of foot 1.obj`,
  sesamoid_bone_of_foot_2: `res/3d-objects/human/${prefiks}/sesamoid bone of foot 2.obj`,
  sesamoid_bone_of_foot_3: `res/3d-objects/human/${prefiks}/sesamoid bone of foot 3.obj`,
  sesamoid_bone_of_foot: `res/3d-objects/human/${prefiks}/sesamoid bone of foot.obj`,
  seventh_cervical_vertebra: `res/3d-objects/human/${prefiks}/seventh cervical vertebra.obj`,
  seventh_thoracic_vertebra: `res/3d-objects/human/${prefiks}/seventh thoracic vertebra.obj`,
  sixth_cervical_vertebra: `res/3d-objects/human/${prefiks}/sixth cervical vertebra.obj`,
  sixth_thoracic_vertebra: `res/3d-objects/human/${prefiks}/sixth thoracic vertebra.obj`,
  sphenoid_bone: `res/3d-objects/human/${prefiks}/sphenoid bone.obj`,
  tenth_thoracic_vertebra: `res/3d-objects/human/${prefiks}/tenth thoracic vertebra.obj`,
  third_cervical_vertebra: `res/3d-objects/human/${prefiks}/third cervical vertebra.obj`,
  third_lumbar_vertebra: `res/3d-objects/human/${prefiks}/third lumbar vertebra.obj`,
  third_thoracic_vertebra: `res/3d-objects/human/${prefiks}/third thoracic vertebra.obj`,
  tooth: `res/3d-objects/human/${prefiks}/tooth.obj`,
  tooth_1: `res/3d-objects/human/${prefiks}/tooth_1.obj`,
  tooth_10: `res/3d-objects/human/${prefiks}/tooth_10.obj`,
  tooth_11: `res/3d-objects/human/${prefiks}/tooth_11.obj`,
  tooth_12: `res/3d-objects/human/${prefiks}/tooth_12.obj`,
  tooth_13: `res/3d-objects/human/${prefiks}/tooth_13.obj`,
  tooth_14: `res/3d-objects/human/${prefiks}/tooth_14.obj`,
  tooth_15: `res/3d-objects/human/${prefiks}/tooth_15.obj`,
  tooth_16: `res/3d-objects/human/${prefiks}/tooth_16.obj`,
  tooth_17: `res/3d-objects/human/${prefiks}/tooth_17.obj`,
  tooth_18: `res/3d-objects/human/${prefiks}/tooth_18.obj`,
  tooth_19: `res/3d-objects/human/${prefiks}/tooth_19.obj`,
  tooth_2: `res/3d-objects/human/${prefiks}/tooth_2.obj`,
  tooth_20: `res/3d-objects/human/${prefiks}/tooth_20.obj`,
  tooth_21: `res/3d-objects/human/${prefiks}/tooth_21.obj`,
  tooth_22: `res/3d-objects/human/${prefiks}/tooth_22.obj`,
  tooth_23: `res/3d-objects/human/${prefiks}/tooth_23.obj`,
  tooth_24: `res/3d-objects/human/${prefiks}/tooth_24.obj`,
  tooth_25: `res/3d-objects/human/${prefiks}/tooth_25.obj`,
  tooth_26: `res/3d-objects/human/${prefiks}/tooth_26.obj`,
  tooth_27: `res/3d-objects/human/${prefiks}/tooth_27.obj`,
  tooth_3: `res/3d-objects/human/${prefiks}/tooth_3.obj`,
  tooth_4: `res/3d-objects/human/${prefiks}/tooth_4.obj`,
  tooth_5: `res/3d-objects/human/${prefiks}/tooth_5.obj`,
  tooth_6: `res/3d-objects/human/${prefiks}/tooth_6.obj`,
  tooth_7: `res/3d-objects/human/${prefiks}/tooth_7.obj`,
  tooth_8: `res/3d-objects/human/${prefiks}/tooth_8.obj`,
  tooth_9: `res/3d-objects/human/${prefiks}/tooth_9.obj`,
  twelfth_thoracic_vertebra: `res/3d-objects/human/${prefiks}/twelfth thoracic vertebra.obj`,
  vomer: `res/3d-objects/human/${prefiks}/vomer.obj`,
  xiphoid_process: `res/3d-objects/human/${prefiks}/xiphoid process.obj`,
};
export default skeletalMap;
