export let map = {
  staticCubes: [],
  staticFloors: [],
  staticObjs: [
    {
      name: "mapobjs_5_6",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 21, y: 1, z: 25.2},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [10, 4, 1],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field56", x: 5, y: 6},
    },
    {
      name: "mapobjs_5_18",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 21, y: 1, z: 75.6},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [10, 4, 1],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field518", x: 5, y: 18},
    },
    {
      name: "mapobjs_5_16",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 21, y: 1, z: 67.2},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [10, 4, 1],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field516", x: 5, y: 16},
    },
  ],
  noPhysics: {cubes: []},
};
