export let map = {
  staticCubes: [],
  staticFloors: [],
  staticObjs: [
    {
      name: "mapobjs_6_8",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 25.2, y: 1, z: 33.6},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field68", x: 6, y: 8},
    },
    {
      name: "mapobjs_6_10",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 25.2, y: 1, z: 42},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field610", x: 6, y: 10},
    },
    {
      name: "mapobjs_6_12",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 25.2, y: 1, z: 50.4},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field612", x: 6, y: 12},
    },
    {
      name: "mapobjs_6_14",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 25.2, y: 1, z: 58.8},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field614", x: 6, y: 14},
    },
    {
      name: "mapobjs_6_16",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 25.2, y: 1, z: 67.2},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field616", x: 6, y: 16},
    },
    {
      name: "mapobjs_6_18",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 25.2, y: 1, z: 75.6},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field618", x: 6, y: 18},
    },
    {
      name: "mapobjs_6_21",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 25.2, y: 1, z: 88.2},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field621", x: 6, y: 21},
    },
    {
      name: "mapobjs_8_21",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 33.6, y: 1, z: 88.2},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field821", x: 8, y: 21},
    },
    {
      name: "mapobjs_7_19",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 29.4, y: 1, z: 79.8},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field719", x: 7, y: 19},
    },
    {
      name: "mapobjs_7_10",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 29.4, y: 1, z: 42},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field710", x: 7, y: 10},
    },
    {
      name: "mapobjs_9_23",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 37.8, y: 1, z: 96.6},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field923", x: 9, y: 23},
    },
    {
      name: "mapobjs_11_25",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 46.2, y: 1, z: 105},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field1125", x: 11, y: 25},
    },
    {
      name: "mapobjs_12_25",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 50.4, y: 1, z: 105},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field1225", x: 12, y: 25},
    },
    {
      name: "mapobjs_12_26",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 50.4, y: 1, z: 109.2},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field1226", x: 12, y: 26},
    },
    {
      name: "mapobjs_13_26",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 54.6, y: 1, z: 109.2},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field1326", x: 13, y: 26},
    },
    {
      name: "mapobjs_16_6",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 67.2, y: 1, z: 25.2},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field166", x: 16, y: 6},
    },
    {
      name: "mapobjs_19_6",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 79.8, y: 1, z: 25.2},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field196", x: 19, y: 6},
    },
    {
      name: "mapobjs_20_6",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 84, y: 1, z: 25.2},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field206", x: 20, y: 6},
    },
    {
      name: "mapobjs_23_8",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 96.6, y: 1, z: 33.6},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field238", x: 23, y: 8},
    },
    {
      name: "mapobjs_23_9",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 96.6, y: 1, z: 37.8},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field239", x: 23, y: 9},
    },
    {
      name: "mapobjs_24_9",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 100.8, y: 1, z: 37.8},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field249", x: 24, y: 9},
    },
    {
      name: "mapobjs_26_14",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 109.2, y: 1, z: 58.8},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field2614", x: 26, y: 14},
    },
    {
      name: "mapobjs_27_15",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 113.4, y: 1, z: 63},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field2715", x: 27, y: 15},
    },
    {
      name: "mapobjs_27_20",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 113.4, y: 1, z: 84},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field2720", x: 27, y: 20},
    },
    {
      name: "mapobjs_27_21",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 113.4, y: 1, z: 88.2},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field2721", x: 27, y: 21},
    },
    {
      name: "mapobjs_27_22",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 113.4, y: 1, z: 92.4},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field2722", x: 27, y: 22},
    },
    {
      name: "mapobjs_24_27",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 100.8, y: 1, z: 113.4},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field2427", x: 24, y: 27},
    },
    {
      name: "mapobjs_24_28",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 100.8, y: 1, z: 117.6},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field2428", x: 24, y: 28},
    },
    {
      name: "mapobjs_19_29",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 79.8, y: 1, z: 121.8},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field1929", x: 19, y: 29},
    },
    {
      name: "mapobjs_18_29",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 75.6, y: 1, z: 121.8},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field1829", x: 18, y: 29},
    },
    {
      name: "mapobjs_17_29",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 71.4, y: 1, z: 121.8},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field1729", x: 17, y: 29},
    },
    {
      name: "mapobjs_15_27",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 63, y: 1, z: 113.4},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field1527", x: 15, y: 27},
    },
    {
      name: "mapobjs_15_28",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 63, y: 1, z: 117.6},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field1528", x: 15, y: 28},
    },
    {
      name: "mapobjs_24_11",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 100.8, y: 1, z: 46.2},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field2411", x: 24, y: 11},
    },
    {
      name: "mapobjs_25_11",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 105, y: 1, z: 46.2},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field2511", x: 25, y: 11},
    },
    {
      name: "mapobjs_25_12",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 105, y: 1, z: 50.4},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field2512", x: 25, y: 12},
    },
    {
      name: "mapobjs_13_6",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 54.6, y: 1, z: 25.2},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field136", x: 13, y: 6},
    },
    {
      name: "mapobjs_15_6",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 63, y: 1, z: 25.2},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field156", x: 15, y: 6},
    },
    {
      name: "mapobjs_11_6",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 46.2, y: 1, z: 25.2},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field116", x: 11, y: 6},
    },
    {
      name: "mapobjs_10_6",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 42, y: 1, z: 25.2},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field106", x: 10, y: 6},
    },
    {
      name: "mapobjs_9_7",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 37.8, y: 1, z: 29.4},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [12, 12, 12],
      scaleCollider: [5, 5, 5],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field97", x: 9, y: 7},
    },
    {
      name: "mapobjs_22_30",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 92.4, y: 1, z: 126},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [24, 24, 24],
      scaleCollider: [10, 10, 10],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field2230", x: 22, y: 30},
    },
    {
      name: "mapobjs_25_17",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 105, y: 1, z: 71.4},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [24, 24, 24],
      scaleCollider: [10, 10, 10],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field2517", x: 25, y: 17},
    },
    {
      name: "mapobjs_26_17",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 109.2, y: 1, z: 71.4},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [24, 24, 24],
      scaleCollider: [10, 10, 10],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field2617", x: 26, y: 17},
    },
    {
      name: "mapobjs_22_20",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 92.4, y: 1, z: 84},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [24, 24, 24],
      scaleCollider: [10, 10, 10],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field2220", x: 22, y: 20},
    },
    {
      name: "mapobjs_17_12",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 71.4, y: 1, z: 50.4},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [24, 24, 24],
      scaleCollider: [10, 10, 10],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field1712", x: 17, y: 12},
    },
    {
      name: "mapobjs_18_12",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 75.6, y: 1, z: 50.4},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [24, 24, 24],
      scaleCollider: [10, 10, 10],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field1812", x: 18, y: 12},
    },
    {
      name: "mapobjs_13_18",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 54.6, y: 1, z: 75.6},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [24, 24, 24],
      scaleCollider: [10, 10, 10],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field1318", x: 13, y: 18},
    },
    {
      name: "mapobjs_17_22",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 71.4, y: 1, z: 92.4},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [24, 24, 24],
      scaleCollider: [10, 10, 10],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field1722", x: 17, y: 22},
    },
    {
      name: "mapobjs_17_23",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 71.4, y: 1, z: 96.6},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [24, 24, 24],
      scaleCollider: [10, 10, 10],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field1723", x: 17, y: 23},
    },
    {
      name: "mapobjs_15_14",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 63, y: 1, z: 58.8},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [24, 24, 24],
      scaleCollider: [10, 10, 10],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field1514", x: 15, y: 14},
    },
    {
      name: "mapobjs_15_15",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 63, y: 1, z: 63},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [24, 24, 24],
      scaleCollider: [10, 10, 10],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field1515", x: 15, y: 15},
    },
    {
      name: "mapobjs_20_15",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 84, y: 1, z: 63},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [24, 24, 24],
      scaleCollider: [10, 10, 10],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field2015", x: 20, y: 15},
    },
    {
      name: "mapobjs_20_16",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 84, y: 1, z: 67.2},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [24, 24, 24],
      scaleCollider: [10, 10, 10],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field2016", x: 20, y: 16},
    },
    {
      name: "mapobjs_21_16",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 88.2, y: 1, z: 67.2},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [24, 24, 24],
      scaleCollider: [10, 10, 10],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field2116", x: 21, y: 16},
    },
    {
      name: "mapobjs_15_20",
      path: "res/3d-objects/env/rock1.obj",
      position: {x: 63, y: 1, z: 84},
      rotation: {rotx: 0, roty: 0, rotz: 0},
      activeRotation: ["0", "0", "0"],
      scale: [24, 24, 24],
      scaleCollider: [10, 10, 10],
      texture: {source: ["res/images/n-stone.png"], mix_operation: "multiply"},
      targetDom: {id: "field1520", x: 15, y: 20},
    },
  ],
  noPhysics: {cubes: []},
};
